# -*- coding: utf-8 -*-
"""Python_While

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bQmjOHp60X_580KuatP8etSnmQRsOdks
"""

#Exercicio_Slide

salario = 100

while salario < 5000:
  salario += 100
  print("O salario ainda e R$", salario) #Atentar para a identacao, caso o print esteja fora do bloco de codigo da condicao "while", o processo sera realizado sem informar o usuario

#EX1

nota = float(input("Insira uma nota entre 0 e 10: "))

while nota <= 0 or nota >= 10:
  print("Nota invalida")
  float(input("Insira uma nota entre 0 e 10: "))

#EX2

soma = 0
contador = 1

n_notas = int(input("Insira a quantidade de  nota a serem calculadas: "))
notas = int(input("Insira a nota: "))

soma = soma + notas

while contador < n_notas:
  contador += 1
  soma = soma + notas
  notas = int(input("Insira a nota: "))

print(f"Media atual: {soma / n_notas}")

#EX3

nome_usuario = str(input("Insira o nome do usuario cadastrado: "))
senha_usuario = str(input("Insira a senha: "))

while senha_usuario == nome_usuario:
  print("Insira uma senha valida")
  str(input("insira a senha: "))
  break

#EX4

ano_inicial = int(input("insira o ano de inicio da analise salarial: "))
salario_inicial = float(input("Insira o salario do funcionario: R$"))
ano_final = int(input("insira o ano final da analise salarial: "))
percentual = 0.015

while ano_inicial < ano_final:
  aumento = salario_inicial * percentual
  salario_inicial += aumento
  percentual *= 2
  ano_inicial += 1
  print(f"R$ {salario_inicial:.2f}")

#EX5

nome = str(input("Insira o nome do usuario: "))
while len(nome) < 3:
  nome = str(input("Insira o nome do usuario: "))

idade = int(input("Insira a idade : "))
while 0 > idade or idade > 150:
  idade = int(input("Insira a idade : "))

salario = float(input("Insira o salario: R$"))
while 0 > salario:
  salario = float(input("Insira o salario: R$"))

sexo = str(input("Insira F ou M para o sexo: " )).upper()
while sexo != "F" and sexo != "M":
  sexo = str(input("Insira F ou M para o sexo: " )).upper()

estado_civil = str(input("Insira S, C, V, D: ")).upper()
while estado_civil != "S" and "C" and "V" and "D":
  estado_civil = str(input("Insira S, C, V, D: ")).upper()

print(f'''
Nome: {nome}
Idade: {idade}
Salario: R${salario}
Sexo {sexo}
Estado civil: {estado_civil}
''')

#EX6

populacao_a = 80000
taxa_anual_a = 0.03

populacao_b = 200000
taxa_anual_b = 0.015

contador = 0

while populacao_a < populacao_b:
  contador += 1
  aumento_a = populacao_a * taxa_anual_a
  aumento_b = populacao_b * taxa_anual_b
  populacao_a = populacao_a + aumento_a
  populacao_b = populacao_b + aumento_b

print(f'''
Anos: {contador}
Populacao A: {populacao_a:.0f}
Populacao B: {populacao_b:.0f}
''')

#EX7

print('''
CANDIDATOS

1 - Jose
2 - Joao
3 - Rafael
4 - Gustavo
5 - Nulo
6 - Branco
''')

voto = int(input("Insira o voto: "))

#while not (1 <= voto <= 6):
  #voto = int(input("Numero invalido: "))

contador = 0